stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myproject
      registry: 10.124.68.86:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker/2
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/singleshot.yml
  when:
    branch:
      include:
      - master
timeout: 20000
branch: {}
notification: {}
