stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myregistry/pipeline:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.124.68.86:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/singleshot.yml
  when:
    branch:
      include:
      - master
timeout: 60
branch: {}
notification: {}
