stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myproject
      pushRemote: true
      registry: 10.124.68.141:30858
    env:
      PLUGIN_DEBUG: "true"
#       PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/singleshot.yaml
  when:
    branch:
      include:
      - master
timeout: 20000
branch: {}
notification: {}
